spring:
  config:
    import: "classpath:application.properties"
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show-sql: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
